apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-deployment
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
        - name: bms
          image: sukhbir25/bms:latest
          ports:
            - containerPort: 3000
          env: []
